version: 2

sources:
  - name: source_bronze
    database: pyspark_dbt 
    schema: bronze 
    tables:
      - name: trips

  - name: source_silver
    database: pyspark_dbt
    schema: silver
    tables:
      - name: customers
      - name: locations
      - name: drivers
      - name: payments
      - name: vehicles